export { setupMainIPC } from './mainHandlers'
export { setupAssistantServerIPC } from './assistantServerHandlers'
export { setupAssistantTogetherIPC } from './assistantHandlers'
export { setupLoggerIPC } from './loggerHandlers'
export { setupUtilityIPC } from './utilityHandlers'
export { setupOnboardingIPC } from './onboardingHandlers'
export { default as setupUpdaterIPC } from './updaterHandlers'
export { default as setupKernelIPC } from './kernelHandlers'
export { setupSystemEventIPC } from './assistantEventHandlers'
export { setupWeatherIPC } from './weatherHandlers'
export { setupLocationIPC } from './locationHandlers'
